const images = {
  sfavot: require("../assets/sfavot.jpg"),
  sonataMaster: require("../assets/slack/sonata-master.png"),
  slack1: require("../assets/slack/slack01.png"),
  magic: require("../assets/slack/slack02.png"),
  heart: require("../assets/coeuraveclesdoigts.jpg"),
  contrib1: require("../assets/slack/contrib/contrib-1.png"),
  contrib2: require("../assets/slack/contrib/contrib-2.png"),
  contrib3: require("../assets/slack/contrib/contrib-3.png"),
  doc1: require("../assets/slack/doc/doc-1.png"),
  doc2: require("../assets/slack/doc/doc-2.png"),
  doc3: require("../assets/slack/doc/doc-3.png"),
  southPark: require("../assets/south-park.gif"),
  fromScratch: require("../assets/slack/from-scratch.png"),
  skeleton: require("../assets/pr-skeleton.jpg"),
  rage1: require("../assets/slack/rage/rage-1.png"),
  rage2: require("../assets/slack/rage/rage-2.png"),
  rage3: require("../assets/slack/rage/rage-3.png"),
  rage4: require("../assets/slack/rage/rage-4.png"),
  rage5: require("../assets/slack/rage/rage-5.png"),
  rage6: require("../assets/slack/rage/rage-6.png"),
  rage7: require("../assets/slack/rage/rage-7.png"),
  rage8: require("../assets/slack/rage/rage-8.png"),
  sonataAdminDashboard: require("../assets/sonata-dashboard.png"),
  sonataAdminList: require("../assets/sonata-list.png"),
  sonataAdminEdit: require("../assets/sonata-edit.png"),
  sonataAdminShow: require("../assets/sonata-show.png"),
  routesPreview1: require("../assets/routes-preview-1.png"),
  routesPreview2: require("../assets/routes-preview-2.png"),
  customActionPreview: require("../assets/custom-action-preview.png"),
  easyAdminJolicampus: require("../assets/easy-admin-jolicampus.png"),
};

export default images;
